# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 811ce72466b257389e462aa3315eb270e8648c81be6d18549958f800d9db6eee176a163966f9defec140c5e4d84d8a1af13f9a2396211736c91c36fbdf55d2ed

test:
  secret_key_base: c596d5ffbeddb9ae68ed77b26a2293b40b633a688efd390ed6a1b2ec27c6c1f9484afef86bc0103fea3db7d513ab6c3f88bcba3e1be1d6b15f66879d52707e1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
